import type { Course, Category } from './types';

export const categories: Category[] = [
  { id: 'all', name: 'All' },
  { id: 'programming', name: 'Programming' },
  { id: 'design', name: 'Design' },
  { id: 'marketing', name: 'Marketing' },
  { id: 'business', name: 'Business' },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'Advanced React Patterns',
    description: 'Master React performance, hooks, and state management.',
    longDescription: 'A deep dive into advanced React concepts for building scalable and performant applications. This course covers everything from reconciliation and fiber architecture to advanced hooks like useReducer and custom hooks. You will also learn various state management strategies including Context API, Zustand, and Redux Toolkit.',
    instructor: 'Jane Doe',
    instructorBio: 'Jane is a Staff Engineer at a FAANG company with over 10 years of experience in frontend development, specializing in the React ecosystem.',
    category: 'programming',
    image: 'https://picsum.photos/600/400?random=1',
    modules: [
      { title: 'Module 1: Performance Optimization', description: 'Learn about memoization, code splitting, and bundle analysis.' },
      { title: 'Module 2: Advanced Hooks', description: 'Explore custom hooks, useReducer, and useContext for complex state.' },
      { title: 'Module 3: State Management', description: 'Compare Redux, MobX, and Zustand for global state management.' },
      { title: 'Module 4: Testing and Debugging', description: 'Master React Testing Library and advanced debugging techniques.' },
    ],
  },
  {
    id: '2',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of creating beautiful and intuitive user interfaces.',
    longDescription: 'This course provides a comprehensive introduction to the world of UI/UX design. You will learn about user research, wireframing, prototyping, and visual design principles. By the end, you\'ll be able to design user-centric digital products that are both functional and aesthetically pleasing.',
    instructor: 'John Smith',
    instructorBio: 'John is a lead product designer with a passion for creating delightful user experiences. He has worked with several successful startups and tech giants.',
    category: 'design',
    image: 'https://picsum.photos/600/400?random=2',
    modules: [
      { title: 'Module 1: Intro to UX', description: 'Understanding user needs and the design thinking process.' },
      { title: 'Module 2: Wireframing & Prototyping', description: 'Creating low-fidelity and high-fidelity prototypes using Figma.' },
      { title: 'Module 3: Visual Design', description: 'Typography, color theory, and layout principles.' },
      { title: 'Module 4: Usability Testing', description: 'Methods for testing your designs with real users.' },
    ],
  },
  {
    id: '3',
    title: 'Digital Marketing Masterclass',
    description: 'A complete guide to SEO, SEM, social media, and content marketing.',
    longDescription: 'Become a digital marketing expert with this all-in-one course. We cover Search Engine Optimization (SEO), Search Engine Marketing (SEM), email marketing, social media strategy, and content creation. You\'ll learn how to grow an online audience and drive sales.',
    instructor: 'Alice Johnson',
    instructorBio: 'Alice is a marketing strategist with a proven track record of growing online businesses through innovative digital campaigns.',
    category: 'marketing',
    image: 'https://picsum.photos/600/400?random=3',
    modules: [
      { title: 'Module 1: SEO Strategy', description: 'On-page, off-page, and technical SEO.' },
      { title: 'Module 2: Paid Advertising', description: 'Google Ads and Facebook Ads campaigns.' },
      { title: 'Module 3: Social Media Marketing', description: 'Building a brand on Instagram, Twitter, and LinkedIn.' },
      { title: 'Module 4: Analytics', description: 'Measuring success with Google Analytics.' },
    ],
  },
  {
    id: '4',
    title: 'Python for Data Science',
    description: 'Learn Python programming and data analysis with Pandas and NumPy.',
    longDescription: 'This course is your first step into the world of data science. Starting with Python basics, you will quickly move on to powerful data manipulation libraries like Pandas and NumPy. You\'ll work on real-world datasets to learn data cleaning, analysis, and visualization.',
    instructor: 'Bob Brown',
    instructorBio: 'Bob is a data scientist with a background in statistics and machine learning. He enjoys making complex topics accessible to beginners.',
    category: 'programming',
    image: 'https://picsum.photos/600/400?random=4',
    modules: [
      { title: 'Module 1: Python Fundamentals', description: 'Variables, data types, loops, and functions.' },
      { title: 'Module 2: NumPy for Numerical Data', description: 'Working with arrays and mathematical operations.' },
      { title: 'Module 3: Pandas for Data Analysis', description: 'DataFrames, data cleaning, and manipulation.' },
      { title: 'Module 4: Data Visualization', description: 'Creating plots with Matplotlib and Seaborn.' },
    ],
  },
    {
    id: '5',
    title: 'Startup Entrepreneurship 101',
    description: 'From idea to MVP to funding: your guide to building a startup.',
    longDescription: 'This course provides a practical, step-by-step guide for aspiring entrepreneurs. Learn how to validate your business idea, build a Minimum Viable Product (MVP), develop a business model, and pitch to investors. We focus on lean startup methodologies to help you succeed.',
    instructor: 'Carol White',
    instructorBio: 'Carol is a serial entrepreneur and angel investor who has built and sold multiple tech companies. She is passionate about mentoring the next generation of founders.',
    category: 'business',
    image: 'https://picsum.photos/600/400?random=5',
    modules: [
      { title: 'Module 1: Idea Validation', description: 'Customer discovery and market research.' },
      { title: 'Module 2: Building an MVP', description: 'Principles of lean product development.' },
      { title: 'Module 3: Business Models', description: 'Crafting a sustainable business model canvas.' },
      { title: 'Module 4: Fundraising', description: 'Understanding venture capital and pitching.' },
    ],
  },
  {
    id: '6',
    title: 'Advanced CSS and Sass',
    description: 'Elevate your styling skills with Flexbox, Grid, and advanced animations.',
    longDescription: 'Move beyond basic CSS and unlock its full potential. This course covers modern layout techniques like Flexbox and CSS Grid, responsive design strategies, and powerful features of Sass. You\'ll also learn to create complex, performant animations and transitions.',
    instructor: 'David Green',
    instructorBio: 'David is a front-end developer and CSS enthusiast who has contributed to several open-source projects and speaks at web development conferences.',
    category: 'design',
    image: 'https://picsum.photos/600/400?random=6',
    modules: [
      { title: 'Module 1: Modern Layouts', description: 'Mastering Flexbox and CSS Grid.' },
      { title: 'Module 2: Advanced Sass', description: 'Mixins, functions, and advanced architecture.' },
      { title: 'Module 3: Animations & Transitions', description: 'Creating fluid and engaging user interfaces.' },
      { title: 'Module 4: Responsive Design', description: 'Mobile-first strategies and modern techniques.' },
    ],
  },
  {
    id: '7',
    title: 'Node.js and Express',
    description: 'Build scalable and robust backend APIs with Node.js.',
    longDescription: 'Learn to build fast and scalable server-side applications with Node.js and the Express framework. This course covers the fundamentals of Node.js, asynchronous programming, building RESTful APIs, and connecting to a database. It\'s perfect for front-end developers looking to go full-stack.',
    instructor: 'Emily Blue',
    instructorBio: 'Emily is a full-stack developer with extensive experience in building microservices and large-scale APIs using the Node.js ecosystem.',
    category: 'programming',
    image: 'https://picsum.photos/600/400?random=7',
    modules: [
      { title: 'Module 1: Node.js Basics', description: 'Event loop, modules, and asynchronous JavaScript.' },
      { title: 'Module 2: Express Framework', description: 'Routing, middleware, and request/response handling.' },
      { title: 'Module 3: RESTful APIs', description: 'Designing and building robust APIs.' },
      { title: 'Module 4: Database Integration', description: 'Connecting to MongoDB with Mongoose.' },
    ],
  },
  {
    id: '8',
    title: 'Content Creation & Strategy',
    description: 'Learn to create compelling content that builds an audience.',
    longDescription: 'This course teaches you the art and science of content strategy. You will learn how to identify your target audience, create a content calendar, write compelling copy, and promote your content across different channels. We cover blogging, video content, and podcasting.',
    instructor: 'Frank Black',
    instructorBio: 'Frank is a content strategist who has helped brands grow their organic reach by millions. He believes in the power of storytelling to connect with people.',
    category: 'marketing',
    image: 'https://picsum.photos/600/400?random=8',
    modules: [
      { title: 'Module 1: Finding Your Niche', description: 'Audience research and content planning.' },
      { title: 'Module 2: The Art of Storytelling', description: 'Crafting narratives that resonate.' },
      { title: 'Module 3: Multi-platform Content', description: 'Adapting content for blogs, YouTube, and podcasts.' },
      { title: 'Module 4: Promotion & Distribution', description: 'Getting your content in front of the right people.' },
    ],
  },
];
